export const namesList = {
  title: "Назва",
  description: "Опис",
  image: "Зображення",
  cores: "Ядра",
  threads: "Потоки",
  vram_quantity: "Пам'ять",
  cache: "Кеш",
  clock: "Частота",
  cost: "Ціна",
  vram_type: "Тип пам'яті",
  Architecture: "Архітектура",
  generation: "Покоління",
  heat_removal: "Відведення тепла",
  type_size: "Розмір",
  memory_quantity: "Обсяг пам'яті",
  reading_speed: "Швидкість читання",
  write_speed: "Швидкість запису",
  chipset: "Чіпсет",
  socket: "Сокет",
  strength: "Потужність",
  sertificate: "Сертифікат",
  radiator_type: "Тип радіатору",
  fan_included: "Інтегровані кулера",
  fan_type: "Тип кулеру",
};
